# Generated by Django 3.2.5 on 2021-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount',
            field=models.PositiveIntegerField(blank=True, help_text='Discount in %', null=True, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.FileField(default='', upload_to='menu_item/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default='', help_text='Name of the item', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price in Tooman', verbose_name='Price (Tooman)'),
            preserve_default=False,
        ),
    ]
