# Generated by Django 3.2.5 on 2021-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210726_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='menu_item/', verbose_name='Image'),
        ),
    ]
